title: "Georges Kanaan"
description: "Simplicity in Mind"
baseurl: ""
url: "https://ge0rges.github.io"
# This uses the built-in "minima" theme from GitHub
theme: minima

# This part below is optional but an example
markdown: kramdown
plugins:
  - jekyll-seo-tag # GitHub built-in plugin for metadata

