name: Compress Images

on: [push]

jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Ensures that GitHub Actions can push the changes

      - name: Compress Images
        uses: ClydeDz/compress-images@v1.0.0
        with:
          input-directory: assets/photos
          output-directory: assets/compressed_photos
          jpg-compression-quality: 40
          png-compression-quality: 0.4
          gif-compression-quality: 4

      - uses: actions/checkout@v3
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/compressed_photos
          git commit -m "Compress images and save output"
          git push
